#!/bin/bash

sudo rm -r /tmp/haproxy-utils-master
sudo rm /tmp/haproxy-utils.zip

# Install 
cd /tmp
sudo apt-get install unzip
sudo apt-get install python-pip
wget https://github.com/ChannelIQ/haproxy-utils/archive/master.zip -O haproxy-utils.zip
unzip haproxy-utils.zip
cd haproxy-utils-master
sudo python setup.py install

# Install webapp
sudo cp -r haproxyadmin /usr/local/bin
sudo cp haproxyadmin/haproxyadmin /etc/init.d
sudo service haproxyadmin start
